export {default as Home} from './home/Home'
export {default as Gigs} from './gigs/Gigs'
export {default as  MyGigs} from './Mygigs/MyGigs'
export{default as Add} from './add/Add'
export {default as Message} from './message/Message'
export {default as Messages} from './messages/Messages'
export {default as Orders} from './orders/Orders'
export {default as Gig} from './gig/Gig'
export {default as Login} from './login/Login'
export {default as Register} from './register/Register'